### web
server.port=8080

# log config
logging.config=classpath:logback.xml

# xxl-cache
### xxl-cache l1 provider, default caffeine
xxl.cache.l1.provider=caffeine
### xxl-cache l1 cache max length, effect if greater than 0, default 10000
xxl.cache.l1.maxSize=-1
### xxl-cache l1 cache expire seconds after write, effect if greater than 0, default 60*10
xxl.cache.l1.expireAfterWrite=-1
### xxl-cache l2 provider, default redis
xxl.cache.l2.provider=redis
### xxl-cache l2 cache serializer, default java
xxl.cache.l2.serializer=java
### xxl-cache l2 cache redis nodes, such as "127.0.0.1:6379"、"127.0.0.1:6379,127.0.0.1:6380"
xxl.cache.l2.nodes=127.0.0.1:6379
### xxl-cache l2 cache redis user
xxl.cache.l2.user=
### xxl-cache l2 cache redis password
xxl.cache.l2.password=
### xxl-cache l2 cache redis database, default 0
xxl.cache.l2.database=0